version: '3.8'

services:
  sdp:
    image: blowxian/sdp:latest
    container_name: sdp
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: always

  sdp_db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sdp_admin
      POSTGRES_PASSWORD: sdp_2024
      POSTGRES_DB: sdp
    volumes:
      - ./data:/var/lib/postgresql/data                           # 持久化数据
    container_name: sdp_db