version: '3.8'

services:
  cosmos_persona:
    image: blowxian/cosmos_persona:latest
    container_name: cosmos_persona
    ports:
      - "3003:3000"
    environment:
      NODE_ENV: production
    restart: always