version: '3.8'
services:
  cosmos_persona:
    build:
      context: .
      args:
        - NODE_ENV=development
      target: development
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - '3002:3000'                                               # 区分于其他分支的端口
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    container_name: cosmos_persona_dev
networks:
  cosmos_persona_dev:
    driver: bridge